from stancedetection.data import loaders as data_loaders

TASK_MAPPINGS = {
    # Stance Benchmark
    "arc": {
        "task_dir": "ARC",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "unrelated", 1: "discuss", 2: "agree", 3: "disagree"},
    },
    "argmin": {
        "task_dir": "ArgMin",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "Argument_against", 1: "Argument_for"},
    },
    "fnc1": {
        "task_dir": "FNC-1",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "unrelated", 1: "discuss", 2: "agree", 3: "disagree"},
    },
    "fnc1-ours": {
        "task_dir": "FNC-1-OURS",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "unrelated", 1: "discuss", 2: "agree", 3: "disagree"},
    },
    "iac1": {
        "task_dir": "IAC",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "anti", 1: "pro", 2: "other"},
    },
    "ibmcs": {
        "task_dir": "IBM_CLAIM_STANCE",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "CON", 1: "PRO"},
    },
    "perspectrum": {
        "task_dir": "PERSPECTRUM",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "UNDERMINE", 1: "SUPPORT"},
    },
    "scd": {
        "task_dir": "SCD",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "against", 1: "for"},
    },
    "semeval2016t6": {
        "task_dir": "SemEval2016Task6",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "AGAINST", 1: "FAVOR", 2: "NONE"},
    },
    "semeval2019t7": {
        "task_dir": "SemEval2019Task7",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "support", 1: "deny", 2: "query", 3: "comment"},
    },
    "snopes": {
        "task_dir": "Snopes",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "refute", 1: "agree"},
    },
    # Others
    "covidlies": {
        "task_dir": "covidlies",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "positive", 1: "negative"},
    },
    "emergent": {
        "task_dir": "emergent",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "against", 1: "for", 2: "observing"},
    },
    "mtsd": {
        "task_dir": "mtsd",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "AGAINST", 1: "FAVOR", 2: "NONE"},
    },
    "poldeb": {
        "task_dir": "politicalDebates",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "for", 1: "against"},
    },
    "rumor": {
        "task_dir": "rumor",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "endorse", 1: "deny", 2: "question", 3: "neutral", 4: "unrelated"},
    },
    "vast": {
        "task_dir": "vast",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "con", 1: "pro", 2: "neutral"},
    },
    "wtwt": {
        "task_dir": "wtwt",
        "loader": data_loaders.StanceBenchmarkLoader,
        "id2label": {0: "comment", 1: "refute", 2: "support", 3: "unrelated"},
    },
    # Multilingual Task Mappings
    "ans": {
        "task_dir": "ANS",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "agree", 1: "disagree", 2: "other"},
        "language": "ar",
    },
    "arabicfc": {
        "task_dir": "ArabicFC",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "agree", 1: "disagree", 2: "discuss", 3: "unrelated"},
        "language": "ar",
    },
    "nlpcc": {
        "task_dir": "Chinese",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "AGAINST", 1: "FAVOR", 2: "NONE"},
        "language": "zh-CN",
    },
    "conref-ita": {
        "task_dir": "ConRef-ITA",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "AGAINST", 1: "FAVOR", 2: "NONE"},
        "language": "it",
    },
    "czech": {
        "task_dir": "Czech",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "Against", 1: "In_favor", 2: "None"},
        "language": "cs",
    },
    "dast": {
        "task_dir": "DAST",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "Commenting", 1: "Denying", 2: "Querying", 3: "Supporting"},
        "language": "da",
    },
    "e-fra": {
        "task_dir": "E-FRA",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "AGAINST", 1: "FAVOUR", 2: "NONE"},
        "language": "fr",
    },
    "hindi": {
        "task_dir": "Hindi",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "AGAINST", 1: "FAVOR", 2: "NONE"},
        "language": "en",
    },
    "iberval2017-ca": {
        "task_dir": "IberEval2017-ca",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "AGAINST", 1: "FAVOR", 2: "NEUTRAL"},
        "language": "ca",
    },
    "iberval2017-es": {
        "task_dir": "IberEval2017-es",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "AGAINST", 1: "FAVOR", 2: "NEUTRAL"},
        "language": "es",
    },
    "r-ita": {
        "task_dir": "R-ITA",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "against", 1: "favor", 2: "none"},
        "language": "it",
    },
    "rustance": {
        "task_dir": "Russian",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "comment", 1: "deny", 2: "query", 3: "support"},
        "language": "ru",
    },
    "sardistance": {
        "task_dir": "SardiStance",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "AGAINST", 1: "FAVOR", 2: "NONE"},
        "language": "it",
    },
    "turkish": {
        "task_dir": "Turkish",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "Against", 1: "Favor"},
        "language": "tr",
    },
    "xstance-de": {
        "task_dir": "XStance-de",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "AGAINST", 1: "FAVOR"},
        "language": "de",
    },
    "xstance-fr": {
        "task_dir": "XStance-fr",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "AGAINST", 1: "FAVOR"},
        "language": "fr",
    },
    "xstance-it": {
        "task_dir": "XStance-it",
        "loader": data_loaders.CrossLingStanceBenchmark,
        "id2label": {0: "AGAINST", 1: "FAVOR"},
        "language": "it",
    },
    # Sentiment
    "wiki": {
        "task_dir": "Wikipedia",
        "loader": data_loaders.SentimentStanceLoader,
        "id2label": {0: "against", 1: "favor", 2: "discuss", 3: "unrelated"},
        "language": "en",
    },
}

DOMAIN_TASK_MAPPINGS = {
    "news": [
        "fnc1",
        "fnc1-ours",
        "emergent",
        "snopes",
    ],
    "social_media": [
        "semeval2016t6",
        "semeval2019t7",
        "covidlies",
        "mtsd",
        "rumor",
        "wtwt",
    ],
    "debates": [
        "iac1",
        "arc",
        "poldeb",
        "perspectrum",
        "scd",
    ],
    "various": [
        "argmin",
        "vast",
        "ibmcs",
    ],
    "multilingual": [
        "ans",
        "arabicfc",
        "nlpcc",
        "conref-ita",
        "czech",
        "dast",
        "e-fra",
        "hindi",
        "iberval2017-ca",
        "iberval2017-es",
        "r-ita",
        "rustance",
        "sardistance",
        "turkish",
        "xstance-de",
        "xstance-fr",
        "xstance-it",
    ],
}

POSITIVE_LABELS = {
    "arc__agree",
    "argmin__Argument_for",
    "fnc1__agree",
    "iac1__pro",
    "perspectrum__SUPPORT",
    "scd__for",
    "semeval2016t6__FAVOR",
    "semeval2019t7__support",
    "snopes__agree",
    "emergent__for",
    "mtsd__FAVOR",
    "poldeb__for",
    "vast__pro",
    "wtwt__support",
    "rumor__endorse",
    "covidlies__positive",
    # Multilingual
    "ans__agree",
    "arabicfc__agree",
    "conref-ita__FAVOR",
    "czech__In favor",
    "dast__Supporting",
    "e-fra__FAVOUR",
    "hindi__FAVOR",
    "iberval2017-ca__FAVOR",
    "iberval2017-es__FAVOR",
    "nlpcc__FAVOR",
    "r-ita__favor",
    "rustance__support",
    "sardistance__FAVOR",
    "turkish__Favor",
    "xstance-de__FAVOR",
    "xstance-fr__FAVOR",
    "xstance-it__FAVOR",
}

NEGATIVE_LABELS = {
    "arc__disagree",
    "argmin__Argument_against",
    "fnc1__disagree",
    "iac1__anti",
    "ibmcs__CON",
    "perspectrum__UNDERMINE",
    "scd__against",
    "semeval2016t6__AGAINST",
    "semeval2019t7__deny",
    "snopes__refute",
    "emergent__against",
    "mtsd__AGAINST",
    "poldeb__against",
    "vast__con",
    "wtwt__refute",
    "rumor__deny",
    "covidlies__negative",
    # Multilingual
    "ans__disagree",
    "arabicfc__disagree",
    "conref-ita__AGAINST",
    "czech__Against",
    "dast__Denying",
    "e-fra__AGAINST",
    "hindi__AGAINST",
    "iberval2017-ca__AGAINST",
    "iberval2017-es__AGAINST",
    "nlpcc__AGAINST",
    "r-ita__against",
    "rustance__deny",
    "sardistance__AGAINST",
    "turkish__Against",
    "xstance-de__AGAINST",
    "xstance-fr__AGAINST",
    "xstance-it__AGAINST",
}

DISCUSS_LABELS = {
    "arc__discuss",
    "fnc1__discuss",
    "semeval2019t7__query",
    "emergent__observing",
    "wtwt__comment",
    "rumor__question",
    # Multilingual
    "arabicfc__discuss",
    "dast__Querying",
    "rustance__query",
}

OTHER_LABELS = {
    "arc__unrelated",
    "fnc1__unrelated",
    "iac1__other",
    "semeval2019t7__comment",
    "mtsd__NONE",
    "wtwt__unrelated",
    "rumor__unrelated",
    # Multilingual
    "ans__other",
    "arabicfc__unrelated",
    "conref-ita__NONE",
    "czech__None",
    "dast__Commenting",
    "e-fra__NONE",
    "hindi__NONE",
    "nlpcc__NONE",
    "r-ita__none",
    "rustance__comment",
    "sardistance__NONE",
}

NEUTRAL_LABELS = {
    "rumor__neutral",
    "vast__neutral",
    # Multilingual
    "iberval2017-ca__NEUTRAL",
    "iberval2017-es__NEUTRAL",
}

RELATED_TASK_MAP = {
    "arc__agree": POSITIVE_LABELS,
    "arc__disagree": NEGATIVE_LABELS,
    "arc__discuss": DISCUSS_LABELS,
    "arc__unrelated": OTHER_LABELS,
    "argmin__Argument_against": NEGATIVE_LABELS,
    "argmin__Argument_for": POSITIVE_LABELS,
    "emergent__against": NEGATIVE_LABELS,
    "emergent__for": POSITIVE_LABELS,
    "emergent__observing": DISCUSS_LABELS,
    "fnc1__agree": POSITIVE_LABELS,
    "fnc1__disagree": NEGATIVE_LABELS,
    "fnc1__discuss": DISCUSS_LABELS,
    "fnc1__unrelated": OTHER_LABELS,
    "iac1__anti": NEGATIVE_LABELS,
    "iac1__other": OTHER_LABELS,
    "iac1__pro": POSITIVE_LABELS,
    "ibmcs__CON": NEGATIVE_LABELS,
    "ibmcs__PRO": POSITIVE_LABELS,
    "mtsd__AGAINST": NEGATIVE_LABELS,
    "mtsd__FAVOR": POSITIVE_LABELS,
    "mtsd__NONE": OTHER_LABELS,
    "perspectrum__SUPPORT": POSITIVE_LABELS,
    "perspectrum__UNDERMINE": NEGATIVE_LABELS,
    "poldeb__against": NEGATIVE_LABELS,
    "poldeb__for": POSITIVE_LABELS,
    "rumor__deny": NEGATIVE_LABELS,
    "rumor__endorse": POSITIVE_LABELS,
    "rumor__neutral": NEUTRAL_LABELS,
    "rumor__question": DISCUSS_LABELS,
    "rumor__unrelated": OTHER_LABELS,
    "scd__against": NEGATIVE_LABELS,
    "scd__for": POSITIVE_LABELS,
    "semeval2016t6__AGAINST": NEGATIVE_LABELS,
    "semeval2016t6__FAVOR": POSITIVE_LABELS,
    "semeval2016t6__NONE": OTHER_LABELS,
    "semeval2019t7__comment": OTHER_LABELS,
    "semeval2019t7__deny": NEGATIVE_LABELS,
    "semeval2019t7__query": DISCUSS_LABELS,
    "semeval2019t7__support": POSITIVE_LABELS,
    "snopes__agree": POSITIVE_LABELS,
    "snopes__refute": NEGATIVE_LABELS,
    "vast__con": NEGATIVE_LABELS,
    "vast__neutral": NEUTRAL_LABELS,
    "vast__pro": POSITIVE_LABELS,
    "wtwt__comment": DISCUSS_LABELS,
    "wtwt__refute": NEGATIVE_LABELS,
    "wtwt__support": POSITIVE_LABELS,
    "wtwt__unrelated": OTHER_LABELS,
    "covidlies__positive": POSITIVE_LABELS,
    "covidlies__negative": NEGATIVE_LABELS,
    # Multilingual
    "ans__agree": POSITIVE_LABELS,
    "ans__disagree": NEGATIVE_LABELS,
    "ans__other": OTHER_LABELS,
    "arabicfc__agree": POSITIVE_LABELS,
    "arabicfc__disagree": NEGATIVE_LABELS,
    "arabicfc__discuss": DISCUSS_LABELS,
    "arabicfc__unrelated": OTHER_LABELS,
    "conref-ita__AGAINST": NEGATIVE_LABELS,
    "conref-ita__FAVOR": POSITIVE_LABELS,
    "conref-ita__NONE": OTHER_LABELS,
    "czech__Against": NEGATIVE_LABELS,
    "czech__In favor": POSITIVE_LABELS,
    "czech__None": OTHER_LABELS,
    "dast__Commenting": OTHER_LABELS,
    "dast__Denying": NEGATIVE_LABELS,
    "dast__Querying": DISCUSS_LABELS,
    "dast__Supporting": POSITIVE_LABELS,
    "e-fra__AGAINST": NEGATIVE_LABELS,
    "e-fra__FAVOUR": POSITIVE_LABELS,
    "e-fra__NONE": OTHER_LABELS,
    "hindi__AGAINST": NEGATIVE_LABELS,
    "hindi__FAVOR": POSITIVE_LABELS,
    "hindi__NONE": OTHER_LABELS,
    "iberval2017-ca__AGAINST": NEGATIVE_LABELS,
    "iberval2017-ca__FAVOR": POSITIVE_LABELS,
    "iberval2017-ca__NEUTRAL": NEUTRAL_LABELS,
    "iberval2017-es__AGAINST": NEGATIVE_LABELS,
    "iberval2017-es__FAVOR": POSITIVE_LABELS,
    "iberval2017-es__NEUTRAL": NEUTRAL_LABELS,
    "nlpcc__AGAINST": NEGATIVE_LABELS,
    "nlpcc__FAVOR": POSITIVE_LABELS,
    "nlpcc__NONE": OTHER_LABELS,
    "r-ita__against": NEGATIVE_LABELS,
    "r-ita__favor": POSITIVE_LABELS,
    "r-ita__none": OTHER_LABELS,
    "rustance__comment": OTHER_LABELS,
    "rustance__deny": NEGATIVE_LABELS,
    "rustance__query": DISCUSS_LABELS,
    "rustance__support": POSITIVE_LABELS,
    "sardistance__AGAINST": NEGATIVE_LABELS,
    "sardistance__FAVOR": POSITIVE_LABELS,
    "sardistance__NONE": OTHER_LABELS,
    "turkish__Against": NEGATIVE_LABELS,
    "turkish__Favor": POSITIVE_LABELS,
    "xstance-de__AGAINST": NEGATIVE_LABELS,
    "xstance-de__FAVOR": POSITIVE_LABELS,
    "xstance-fr__AGAINST": NEGATIVE_LABELS,
    "xstance-fr__FAVOR": POSITIVE_LABELS,
    "xstance-it__AGAINST": NEGATIVE_LABELS,
    "xstance-it__FAVOR": POSITIVE_LABELS,
}

TGT_CTX_PREFIXES = {
    "arc": {
        "premise": "Headline",
        "hypothesis": "Post",
    },
    "argmin": {
        "premise": "Topic",
        "hypothesis": "Sentence",
    },
    "emergent": {
        "premise": "Headline",
        "hypothesis": "Article",
    },
    "fnc1": {
        "premise": "Headline",
        "hypothesis": "Article",
    },
    "iac1": {
        "premise": "Topic",
        "hypothesis": "Post",
    },
    "ibmcs": {
        "premise": "Topic",
        "hypothesis": "Claim",
    },
    "mtsd": {
        "premise": "Person",
        "hypothesis": "Tweet",
    },
    "perspectrum": {
        "premise": "Claim",
        "hypothesis": "Sentence",
    },
    "poldeb": {
        "premise": "Topic",
        "hypothesis": "Post",
    },
    "rumor": {
        "premise": "Topic",
        "hypothesis": "Tweet",
    },
    "scd": {
        "premise": "Topic",
        "hypothesis": "Post",
    },
    "semeval2016t6": {
        "premise": "Topic",
        "hypothesis": "Tweet",
    },
    "semeval2019t7": {
        "premise": "Topic",
        "hypothesis": "Tweet",
    },
    "snopes": {
        "premise": "Claim",
        "hypothesis": "Article",
    },
    "vast": {
        "premise": "Topic",
        "hypothesis": "Post",
    },
    "wtwt": {
        "premise": "Claim",
        "hypothesis": "Tweet",
    },
    "ans": {
        "hypothesis": "Title",
        "premise": "Title",
    },
    "arabicfc": {
        "hypothesis": "Article",
        "premise": "Claim",
    },
    "nlpcc": {
        "hypothesis": "Post",
        "premise": "Topic",
    },
    "conref-ita": {
        "hypothesis": "Tweet",
        "premise": "Tweet",
    },
    "czech": {
        "hypothesis": "Comment",
        "premise": "Topic",
    },
    "hindi": {
        "hypothesis": "Tweet",
        "premise": "Topic",
    },
    "rustance": {
        # Tweet
        "hypothesis": "Comment",
        "premise": "Claim",
    },
    "turkish": {
        "hypothesis": "Tweet",
        "premise": "Topic",
    },
    "xstance-de": {
        "hypothesis": "Answer",
        "premise": "Question",
    },
    "xstance-fr": {
        "hypothesis": "Answer",
        "premise": "Question",
    },
    "xstance-it": {
        "hypothesis": "Answer",
        "premise": "Question",
    },
    "e-fra": {
        "hypothesis": "Tweet",
        "premise": "Person",
    },
    "r-ita": {
        "hypothesis": "Tweet",
        "premise": "Topic",
    },
    "dast": {
        "hypothesis": "Post",
        # Claim Topic
        "premise": "Claim",
    },
    "iberval2017-ca": {
        "hypothesis": "Tweet",
        "premise": "Topic",
    },
    "iberval2017-es": {
        "hypothesis": "Tweet",
        "premise": "Topic",
    },
    "sardistance": {
        "hypothesis": "Tweet",
        "premise": "Topic",
    },
}

ID2PREFIX = {
    "Claim": 0,
    "Title": 1,
    "Question": 2,
    "Article": 3,
    "Sentence": 4,
    "Headline": 5,
    "Tweet": 6,
    "Topic": 7,
    "Post": 8,
    "Person": 9,
    "Answer": 10,
    "Comment": 11,
}
