SYNONYM_THESAURUS = {
    "against": [
        "abutting",
        "adjacent to",
        "against",
        "antagonistic towards",
        "as provision for",
        "at odds with",
        "at variance with",
        "averse to",
        "close up to",
        "contra",
        "contrarily",
        "contrariwise",
        "contrary to",
        "conversely",
        "hostile to",
        "in anticipation of",
        "in case of",
        "in contact with",
        "in contravention of",
        "in defiance of",
        "in disagreement with",
        "in expectation of",
        "in opposition to",
        "in preparation for",
        "in provision for",
        "inimical to",
        "on",
        "opposed to",
        "resistant to",
        "touching",
        "unsympathetic to",
        "up against",
    ],
    "agree": [
        "accede",
        "accord",
        "assent",
        "be acceptable to",
        "be agreeable to",
        "be as one man",
        "be compatible",
        "be congruous",
        "be consistent",
        "be consonant",
        "be equivalent",
        "be good for",
        "be healthy for",
        "be in agreement",
        "be in harmony",
        "be in sympathy",
        "be in tune",
        "be of the same mind",
        "be of the same opinion",
        "be parallel",
        "be united",
        "check",
        "chime",
        "coincide",
        "concord",
        "concur",
        "conform",
        "consent",
        "consort",
        "correlate",
        "correspond",
        "dovetail",
        "equate",
        "fit",
        "fit in",
        "gibe",
        "harmonise",
        "harmonize",
        "hold",
        "jibe",
        "match",
        "match up",
        "see eye to eye",
        "suit",
        "sympathize",
        "tally",
    ],
    "anti": [
        "antagonistic",
        "antagonistic towards",
        "at odds with",
        "averse",
        "averse to",
        "contra",
        "hostile",
        "hostile to",
        "ill-disposed",
        "in disagreement with",
        "in opposition to",
        "inimical to",
        "opposed",
        "opposed to",
        "resistant to",
        "unsympathetic",
        "unsympathetic to",
    ],
    "comment": [
        "allude to",
        "annotate",
        "commentary",
        "criticism",
        "discuss",
        "express an opinion on",
        "give a mention to",
        "gloss",
        "gossip",
        "input",
        "judgement",
        "make a comment on",
        "make mention of",
        "make remarks about",
        "mention",
        "notice",
        "observation",
        "opinion",
        "point out",
        "pronouncement",
        "reflection",
        "remark",
        "remark on",
        "say something about",
        "scuttlebutt",
        "speak about",
        "statement",
        "talk about",
        "touch on",
        "utterance",
        "view",
        "write about",
    ],
    "commenting": [
        "allude to",
        "annotate",
        "comment",
        "criticism",
        "discuss",
        "express an opinion on",
        "give a mention to",
        "gloss",
        "judgement",
        "make a comment on",
        "make mention of",
        "make remarks about",
        "mention",
        "notice",
        "observation",
        "opinion",
        "point out",
        "pronouncement",
        "reflection",
        "remark",
        "remark on",
        "say something about",
        "speak about",
        "statement",
        "talk about",
        "touch on",
        "utterance",
        "view",
        "write about",
    ],
    "con": [
        "bit of sharp practice",
        "bleed",
        "bunco",
        "bunco game",
        "bunko",
        "bunko game",
        "cheat",
        "con game",
        "confidence game",
        "confidence trick",
        "convict",
        "deceive",
        "deception",
        "defraud",
        "diddle",
        "dupe",
        "exploit",
        "fleece",
        "flimflam",
        "fraud",
        "gip",
        "goldbrick",
        "gyp",
        "hornswoggle",
        "hustle",
        "inmate",
        "learn",
        "memorise",
        "memorize",
        "milk",
        "mulct",
        "nobble",
        "racket",
        "rook",
        "scam",
        "short-change",
        "squeeze",
        "sting",
        "swindle",
        "trick",
        "victimize",
        "yard bird",
        "yardbird",
    ],
    "deny": [
        "abnegate",
        "challenge",
        "contest",
        "contradict",
        "declare untrue",
        "decline",
        "disagree with",
        "dismiss",
        "dissent from",
        "gainsay",
        "oppose",
        "rebuff",
        "refuse",
        "reject",
        "repudiate",
        "repulse",
        "traverse",
        "turn down",
        "veto",
    ],
    "denying": [
        "abnegate",
        "challenge",
        "contest",
        "contradict",
        "declare untrue",
        "decline",
        "deny",
        "disagree with",
        "dismiss",
        "dissent from",
        "gainsay",
        "oppose",
        "rebuff",
        "refuse",
        "reject",
        "repudiate",
        "repulse",
        "traverse",
        "turn down",
        "veto",
    ],
    "disagree": [
        "be at odds",
        "be at variance",
        "be different",
        "be dissimilar",
        "be in contention",
        "be in dispute",
        "be unlike",
        "differ",
        "differ from",
        "disaccord",
        "discord",
        "dissent",
        "dissent from",
        "diverge from",
        "fail to agree",
        "not see eye to eye",
        "take issue",
        "vary",
    ],
    "discuss": [
        "argue",
        "chew over",
        "confer about",
        "consider",
        "consider the pros and cons of",
        "converse about",
        "debate",
        "deliberate about",
        "discourse",
        "discus",
        "dispute",
        "exchange views about",
        "exchange views on",
        "hash out",
        "put your heads together about",
        "saucer",
        "talk about",
        "talk over",
        "talk through",
        "thrash out",
        "weigh up",
    ],
    "endorse": [
        "agree to",
        "approve",
        "approve of",
        "assent to",
        "autograph",
        "back",
        "certify",
        "confirm",
        "consent to",
        "countersign",
        "defend",
        "endorse",
        "indorse",
        "initial",
        "inscribe",
        "maintain",
        "plump for",
        "plunk for",
        "put one's mark on",
        "ratify",
        "sanction",
        "second",
        "sign on the back",
        "superscribe",
        "support",
        "uphold",
    ],
    "favor": [
        "accommodate",
        "act of kindness",
        "approbation",
        "approval",
        "be like",
        "be similar to",
        "bear a resemblance to",
        "benevolence",
        "choice",
        "chosen",
        "commendation",
        "courtesy",
        "esteem",
        "favour",
        "favourite",
        "friendliness",
        "good deed",
        "good turn",
        "goodwill",
        "gratify",
        "have the look of",
        "humour",
        "ideal",
        "indulge",
        "indulgence",
        "kind act",
        "kindness",
        "look like",
        "most-liked",
        "oblige",
        "pander to",
        "particular",
        "party favor",
        "party favour",
        "pet",
        "prefer",
        "preferred",
        "privilege",
        "put one in mind of",
        "put oneself out for",
        "recommended",
        "remind one of",
        "resemble",
        "satisfy",
        "selected",
        "service",
        "special",
        "take after",
    ],
    "favour": [
        "accommodate",
        "act of kindness",
        "alms",
        "approbation",
        "approval",
        "award",
        "be like",
        "be similar to",
        "bear a resemblance to",
        "benefaction",
        "benevolence",
        "bequest",
        "bestowal",
        "bonus",
        "boon",
        "bounty",
        "charity",
        "choice",
        "chosen",
        "commendation",
        "contribution",
        "courtesy",
        "donation",
        "endowment",
        "esteem",
        "favor",
        "favour",
        "favourite",
        "friendliness",
        "good deed",
        "good turn",
        "goodwill",
        "grant",
        "gratify",
        "handout",
        "have the look of",
        "humour",
        "ideal",
        "indulge",
        "indulgence",
        "inheritance",
        "kind act",
        "kindness",
        "largesse",
        "legacy",
        "look like",
        "most-liked",
        "oblige",
        "offering",
        "pander to",
        "particular",
        "party favor",
        "party favour",
        "pet",
        "prefer",
        "preferred",
        "premium",
        "present",
        "presentation",
        "privilege",
        "put one in mind of",
        "put oneself out for",
        "recommended",
        "remind one of",
        "resemble",
        "satisfy",
        "selected",
        "service",
        "settlement",
        "special",
        "subsidy",
        "take after",
    ],
    "for": [
        "aim",
        "all for",
        "approving of",
        "as a mark of respect to",
        "as a tribute to",
        "because",
        "cause",
        "considering that",
        "encouraging of",
        "end",
        "for",
        "giving backing to",
        "giving support to",
        "goal",
        "in honour of",
        "in view of the fact that",
        "motive",
        "object",
        "objective",
        "on account of the fact that",
        "on the side of",
        "owing to the fact that",
        "pro",
        "purpose",
        "reason",
        "right behind",
        "seeing as",
        "seeing that",
        "since",
        "sympathetic to",
        "the same as",
    ],
    "negative": [
        "anti",
        "antipathetic",
        "blackball",
        "bleak",
        "cancel out",
        "counteract",
        "cynical",
        "damaging",
        "defeatist",
        "disconfirming",
        "dismissive",
        "electronegative",
        "fatalistic",
        "gloom-ridden",
        "gloomy",
        "minus",
        "negate",
        "negatively charged",
        "neutralize",
        "no",
        "nullify",
        "obstructive",
        "pessimistic",
        "refusal",
        "refuse",
        "reject",
        "rejection",
        "render ineffective",
        "say \u2018no\u2019 to",
        "squash",
        "turn down",
        "uncooperative",
        "veto",
    ],
    "neutral": [
        "achromatic",
        "anodyne",
        "bland",
        "clinical",
        "commonplace",
        "detached",
        "disinterested",
        "dispassionate",
        "electroneutral",
        "equitable",
        "even-handed",
        "everyday",
        "fair",
        "fair-minded",
        "impartial",
        "impersonal",
        "indifferent",
        "inert",
        "inoffensive",
        "non-discriminatory",
        "non-partisan",
        "objective",
        "open-minded",
        "ordinary",
        "removed",
        "run-of-the-mill",
        "unbiased",
        "unemotional",
        "unexceptionable",
        "unobjectionable",
        "unprejudiced",
        "unremarkable",
        "without favouritism",
    ],
    "none": [
        "by no means any",
        "in no way",
        "not a bit",
        "not a one",
        "not at all",
        "not for a moment",
        "not one",
        "not the slightest bit",
        "to no extent",
    ],
    "observing": [
        "abide by",
        "accept",
        "acquiesce in",
        "adhere to",
        "announce",
        "be heedful of",
        "celebrate",
        "comment",
        "comply with",
        "conform to",
        "consent to",
        "declare",
        "defer to",
        "detect",
        "discern",
        "discover",
        "distinguish",
        "find",
        "follow",
        "fulfil",
        "heed",
        "honor",
        "honour",
        "interject",
        "interpose",
        "keep",
        "keep an eye on",
        "maintain",
        "make out",
        "mention",
        "note",
        "notice",
        "obey",
        "observant",
        "observe",
        "pay attention to",
        "perceive",
        "pronounce",
        "remark",
        "respect",
        "say",
        "see",
        "spot",
        "stand by",
        "state",
        "take note",
        "utter",
        "watch",
        "watch over",
    ],
    "other": [
        "added",
        "additional",
        "early",
        "extra",
        "former",
        "further",
        "more",
        "supplemental",
        "supplementary",
    ],
    "positive": [
        "absolute",
        "actual",
        "beneficial",
        "beyond a doubt",
        "beyond question",
        "categorical",
        "certain",
        "clear",
        "clear-cut",
        "cocksure",
        "conclusive",
        "concrete",
        "confident",
        "confirming",
        "constructive",
        "convinced",
        "convincing",
        "decisive",
        "definite",
        "direct",
        "effective",
        "efficacious",
        "electropositive",
        "explicit",
        "express",
        "firm",
        "helpful",
        "incontestable",
        "incontrovertible",
        "indisputable",
        "indubitable",
        "irrefutable",
        "overconfident",
        "persuasive",
        "plus",
        "positive degree",
        "positively charged",
        "positivist",
        "positivistic",
        "practical",
        "pragmatic",
        "precise",
        "prescribed",
        "productive",
        "real",
        "reliable",
        "tangible",
        "unambiguous",
        "undeniable",
        "unequivocal",
        "unmistakable",
        "unquestionable",
        "useful",
        "worthwhile",
    ],
    "pro": [
        "added advantage",
        "added extra",
        "additional benefit",
        "advantage",
        "all for",
        "approving",
        "approving of",
        "asset",
        "attraction",
        "attractive feature",
        "beauty",
        "benefit",
        "bonus",
        "dividend",
        "encouraging of",
        "extra",
        "for",
        "fringe benefit",
        "giving backing to",
        "giving support to",
        "good point",
        "in favour",
        "non-amateur",
        "on the side of",
        "paid player",
        "perk",
        "plus point",
        "professional",
        "professional player",
        "right behind",
        "sympathetic to",
    ],
    "in favour": [
        "added advantage",
        "added extra",
        "additional benefit",
        "advantage",
        "all for",
        "approving",
        "approving of",
        "asset",
        "attraction",
        "attractive feature",
        "beauty",
        "benefit",
        "bonus",
        "dividend",
        "encouraging of",
        "extra",
        "for",
        "fringe benefit",
        "giving backing to",
        "giving support to",
        "good point",
        "non-amateur",
        "on the side of",
        "paid player",
        "perk",
        "plus point",
        "pro",
        "right behind",
        "sympathetic to",
    ],
    "in favor": [
        "added advantage",
        "added extra",
        "additional benefit",
        "advantage",
        "all for",
        "approving",
        "approving of",
        "asset",
        "attraction",
        "attractive feature",
        "beauty",
        "benefit",
        "bonus",
        "dividend",
        "encouraging of",
        "extra",
        "for",
        "fringe benefit",
        "giving backing to",
        "giving support to",
        "good point",
        "non-amateur",
        "on the side of",
        "paid player",
        "perk",
        "plus point",
        "pro",
        "right behind",
        "sympathetic to",
    ],
    "query": ["ask", "enquiry", "inquire", "inquiry", "interrogation", "question"],
    "querying": ["ask", "inquire", "inquiry", "query", "question"],
    "question": [
        "ask questions of",
        "call into question",
        "canvass",
        "catechize",
        "cross-examine",
        "cross-question",
        "debrief",
        "doubt",
        "doubtfulness",
        "dubiousness",
        "enquiry",
        "examine",
        "give the third degree to",
        "head",
        "inquiry",
        "interrogate",
        "interrogation",
        "interrogative",
        "interrogative sentence",
        "interview",
        "motion",
        "oppugn",
        "probe",
        "put questions to",
        "query",
        "quiz",
        "sound out",
        "wonder",
    ],
    "refute": [
        "confute",
        "controvert",
        "debunk",
        "demolish",
        "discredit",
        "disprove",
        "drive a coach and horses through",
        "explode",
        "give the lie to",
        "invalidate",
        "prove false",
        "prove to be false",
        "prove to be wrong",
        "prove wrong",
        "rebut",
        "show to be false",
        "show to be wrong",
    ],
    "support": [
        "abide",
        "accompaniment",
        "affirm",
        "aid",
        "assist",
        "attest to",
        "authenticate",
        "back",
        "back up",
        "backing",
        "backup",
        "base",
        "bear",
        "bear out",
        "bolster up",
        "brace",
        "bread and butter",
        "brook",
        "buttress",
        "carry",
        "confirm",
        "corroborate",
        "defend",
        "digest",
        "document",
        "documentation",
        "endorse",
        "endure",
        "fend for",
        "financial backing",
        "financial support",
        "foundation",
        "funding",
        "give force to",
        "give weight to",
        "help",
        "hold",
        "hold up",
        "indorse",
        "keep",
        "keep going",
        "keep up",
        "livelihood",
        "living",
        "maintenance",
        "musical accompaniment",
        "patronage",
        "patronise",
        "patronize",
        "pillar",
        "plump for",
        "plunk for",
        "post",
        "prop",
        "prop up",
        "prove",
        "put up",
        "put up with",
        "ratify",
        "reenforcement",
        "reinforce",
        "reinforcement",
        "shore up",
        "shoulder",
        "stand",
        "stick out",
        "stomach",
        "subscribe",
        "subsistence",
        "substantiate",
        "substructure",
        "suffer",
        "supporting",
        "sustain",
        "sustenance",
        "tolerate",
        "underpin",
        "underpinning",
        "underprop",
        "validate",
        "verify",
        "weather",
    ],
    "supporting": [
        "abide",
        "affirm",
        "back",
        "back up",
        "bear",
        "bear out",
        "brook",
        "confirm",
        "corroborate",
        "defend",
        "digest",
        "encouraging",
        "endorse",
        "endure",
        "fend for",
        "hold",
        "hold up",
        "indorse",
        "keep going",
        "load-bearing",
        "patronage",
        "patronise",
        "patronize",
        "plump for",
        "plunk for",
        "put up",
        "stand",
        "stick out",
        "stomach",
        "subscribe",
        "substantiate",
        "suffer",
        "support",
        "sustain",
        "tolerate",
        "underpin",
    ],
    "undermine": [
        "cave",
        "chip away",
        "compromise",
        "counteract",
        "countermine",
        "cripple",
        "damage",
        "diminish",
        "disable",
        "eat away at",
        "enfeeble",
        "erode",
        "hinder",
        "hurt",
        "impair",
        "impede",
        "injure",
        "mar",
        "reduce",
        "ruin",
        "sabotage",
        "sap",
        "shake",
        "spoil",
        "subvert",
        "threaten",
        "undercut",
        "weaken",
        "wear away",
    ],
    "unrelated": [
        "discrete",
        "distinct",
        "independent",
        "individual",
        "separate",
        "unallied",
        "unassociated",
        "unattached",
        "unconnected",
        "uncoupled",
        "unlinked",
    ],
}

SYNONYM_THESAURUS_MULTILINGUAL = {
    "denying": {
        "ar": "إنكار",
        "ca": "negant",
        "cs": "popírat",
        "da": "benægter",
        "de": "leugnen",
        "es": "negando",
        "fr": "nier",
        "hi": "इस बात का खंडन",
        "it": "negare",
        "ru": "отрицание",
        "tr": "inkar",
        "zh": "denying",
        "zh-CN": "否认",
    },
    "argument_against": {
        "ar": "مجادلة ضد",
        "ca": "argument en contra",
        "cs": "argument proti",
        "da": "argument mod",
        "de": "gegenargument",
        "es": "argumento en contra",
        "fr": "argument contre",
        "hi": "के खिलाफ बहस",
        "it": "argomento contro",
        "ru": "аргумент против",
        "tr": "karşıt arguman",
        "zh": "argument against",
        "zh-CN": "反对",
    },
    "comment": {
        "ar": "تعليق",
        "ca": "comentari",
        "cs": "komentář",
        "da": "kommentar",
        "de": "kommentar",
        "es": "comentario",
        "fr": "commenter",
        "hi": "टिप्पणी",
        "it": "commento",
        "ru": "комментарий",
        "tr": "yorum yap",
        "zh": "comment",
        "zh-CN": "评论",
    },
    "none": {
        "ar": "لا أحد",
        "ca": "cap",
        "cs": "žádný",
        "da": "ingen",
        "de": "keiner",
        "es": "ninguno",
        "fr": "rien",
        "hi": "कोई नहीं",
        "it": "nessuna",
        "ru": "никто",
        "tr": "yok",
        "zh": "none",
        "zh-CN": "没有任何",
    },
    "pro": {
        "ar": "طليعة",
        "ca": "pro",
        "cs": "pro",
        "da": "pro",
        "de": "profi",
        "es": "pro",
        "fr": "pro",
        "hi": "समर्थक",
        "it": "pro",
        "ru": "профи",
        "tr": "profesyonel",
        "zh": "pro",
        "zh-CN": "亲",
    },
    "observing": {
        "ar": "المراقبة",
        "ca": "observant",
        "cs": "pozorování",
        "da": "observerer",
        "de": "beobachten",
        "es": "observando",
        "fr": "observant",
        "hi": "अवलोकन",
        "it": "osservando",
        "ru": "наблюдение",
        "tr": "gözlem",
        "zh": "observing",
        "zh-CN": "观察",
    },
    "support": {
        "ar": "الدعم",
        "ca": "suport",
        "cs": "podpěra, podpora",
        "da": "support",
        "de": "unterstützung",
        "es": "apoyo",
        "fr": "support",
        "hi": "सहयोग",
        "it": "supporto",
        "ru": "служба поддержки",
        "tr": "destek",
        "zh": "support",
        "zh-CN": "支持",
    },
    "other": {
        "ar": "آخر",
        "ca": "altres",
        "cs": "jiný",
        "da": "andet",
        "de": "andere",
        "es": "otro",
        "fr": "autre",
        "hi": "अन्य",
        "it": "altro",
        "ru": "другие",
        "tr": "diğer",
        "zh": "other",
        "zh-CN": "其他",
    },
    "commenting": {
        "ar": "التعليق",
        "ca": "comentant",
        "cs": "komentování",
        "da": "kommenterer",
        "de": "kommentieren",
        "es": "comentando",
        "fr": "commenter",
        "hi": "टिप्पणी",
        "it": "commentando",
        "ru": "комментируя",
        "tr": "yorum yapma",
        "zh": "commenting",
        "zh-CN": "评论",
    },
    "neutral": {
        "ar": "حيادي",
        "ca": "neutre",
        "cs": "neutrální",
        "da": "neutral",
        "de": "neutral",
        "es": "neutral",
        "fr": "neutre",
        "hi": "तटस्थ",
        "it": "neutro",
        "ru": "нейтральный",
        "tr": "tarafsız",
        "zh": "neutral",
        "zh-CN": "中性的",
    },
    "positive": {
        "ar": "إيجابي",
        "ca": "positiu",
        "cs": "pozitivní",
        "da": "positiv",
        "de": "positiv",
        "es": "positivo",
        "fr": "positif",
        "hi": "सकारात्मक",
        "it": "positivo",
        "ru": "положительный",
        "tr": "pozitif",
        "zh": "positive",
        "zh-CN": "积极的",
    },
    "agree": {
        "ar": "يوافق على",
        "ca": "acordar",
        "cs": "souhlasit",
        "da": "enig",
        "de": "zustimmen",
        "es": "estar de acuerdo",
        "fr": "je suis d'accord",
        "hi": "इस बात से सहमत",
        "it": "essere d'accordo",
        "ru": "дать согласие",
        "tr": "katılıyorum",
        "zh": "agree",
        "zh-CN": "同意",
    },
    "undermine": {
        "ar": "تقويض",
        "ca": "minar",
        "cs": "podkopat",
        "da": "underminere",
        "de": "untergraben",
        "es": "socavar",
        "fr": "saper",
        "hi": "कमजोर",
        "it": "minare",
        "ru": "подорвать",
        "tr": "baltalamak",
        "zh": "undermine",
        "zh-CN": "破坏",
    },
    "querying": {
        "ar": "الاستعلام",
        "ca": "consultant",
        "cs": "dotazování",
        "da": "forespørgsel",
        "de": "abfragen",
        "es": "preguntando",
        "fr": "interrogation",
        "hi": "क्वेरी",
        "it": "interrogare",
        "ru": "запрос",
        "tr": "sorgulama",
        "zh": "querying",
        "zh-CN": "查询",
    },
    "for": {
        "ar": "ل",
        "ca": "per",
        "cs": "pro",
        "da": "til",
        "de": "zum",
        "es": "por",
        "fr": "pour",
        "hi": "के लिये",
        "it": "per",
        "ru": "для",
        "tr": "için",
        "zh": "for",
        "zh-CN": "为了",
    },
    "con": {
        "ar": "يخدع",
        "ca": "con",
        "cs": "ošidit",
        "da": "con",
        "de": "con",
        "es": "estafa",
        "fr": "con",
        "hi": "चोर",
        "it": "con",
        "ru": "против",
        "tr": "con",
        "zh": "with",
        "zh-CN": "骗局",
    },
    "negative": {
        "ar": "نفي",
        "ca": "negatiu",
        "cs": "záporný",
        "da": "negativ",
        "de": "negativ",
        "es": "negativo",
        "fr": "négatif",
        "hi": "नकारात्मक",
        "it": "negativo",
        "ru": "отрицательный",
        "tr": "olumsuz",
        "zh": "negative",
        "zh-CN": "消极的",
    },
    "refute": {
        "ar": "دحض",
        "ca": "refutar",
        "cs": "vyvrátit",
        "da": "tilbagevise",
        "de": "widerlegen",
        "es": "refutar",
        "fr": "réfuter",
        "hi": "खंडन",
        "it": "confutare",
        "ru": "опровергать",
        "tr": "yalanlamak",
        "zh": "refute",
        "zh-CN": "反驳",
    },
    "deny": {
        "ar": "أنكر",
        "ca": "negar",
        "cs": "odmítnout",
        "da": "nægte",
        "de": "verweigern",
        "es": "negar",
        "fr": "nier",
        "hi": "मना",
        "it": "negare",
        "ru": "отказываться от",
        "tr": "reddetmek",
        "zh": "deny",
        "zh-CN": "否定",
    },
    "endorse": {
        "ar": "تصادق",
        "ca": "avalar",
        "cs": "podpořit",
        "da": "godkende",
        "de": "befürworten",
        "es": "endosar",
        "fr": "endosser",
        "hi": "समर्थन",
        "it": "approvare",
        "ru": "одобрять",
        "tr": "onaylamak",
        "zh": "endorse",
        "zh-CN": "赞同",
    },
    "supporting": {
        "ar": "دعم",
        "ca": "suport",
        "cs": "vedlejší",
        "da": "støtte",
        "de": "unterstützen",
        "es": "secundario",
        "fr": "justificatif",
        "hi": "सहायक",
        "it": "supporto",
        "ru": "поддерживающий",
        "tr": "destekleyici",
        "zh": "supporting",
        "zh-CN": "配套",
    },
    "query": {
        "ar": "استفسار",
        "ca": "consulta",
        "cs": "dotaz",
        "da": "forespørgsel",
        "de": "abfrage",
        "es": "consulta",
        "fr": "mettre en doute",
        "hi": "सवाल",
        "it": "query",
        "ru": "запрос",
        "tr": "sorgu",
        "zh": "query",
        "zh-CN": "询问",
    },
    "favour": {
        "ar": "محاباة",
        "ca": "favor",
        "cs": "laskavost",
        "da": "favor",
        "de": "bevorzugen",
        "es": "favor",
        "fr": "préférer",
        "hi": "एहसान",
        "it": "favore",
        "ru": "услуга",
        "tr": "iyilik",
        "zh": "favour",
        "zh-CN": "宠爱",
    },
    "question": {
        "ar": "سؤال",
        "ca": "pregunta",
        "cs": "otázka",
        "da": "spørgsmål",
        "de": "frage",
        "es": "pregunta",
        "fr": "question",
        "hi": "सवाल",
        "it": "domanda",
        "ru": "вопрос",
        "tr": "soru",
        "zh": "question",
        "zh-CN": "问题",
    },
    "in_favor": {
        "ar": "لصالح",
        "ca": "a favor",
        "cs": "ve prospěch",
        "da": "til fordel",
        "de": "zugunsten",
        "es": "a favor",
        "fr": "en faveur",
        "hi": "पक्ष में",
        "it": "in favore",
        "ru": "в пользу",
        "tr": "lehine",
        "zh": "in favor",
        "zh-CN": "赞同，支持，受赏识，有利",
    },
    "discuss": {
        "ar": "مناقشة",
        "ca": "discutir",
        "cs": "diskutovat",
        "da": "drøfte",
        "de": "diskutieren",
        "es": "discutir",
        "fr": "discuter",
        "hi": "चर्चा करें",
        "it": "discutere",
        "ru": "обсуждать",
        "tr": "tartışmak",
        "zh": "discuss",
        "zh-CN": "讨论",
    },
    "anti": {
        "ar": "مضاد",
        "ca": "anti",
        "cs": "proti",
        "da": "anti",
        "de": "anti",
        "es": "anti",
        "fr": "anti",
        "hi": "एंटी",
        "it": "anti",
        "ru": "анти",
        "tr": "anti",
        "zh": "anti",
        "zh-CN": "反对",
    },
    "unrelated": {
        "ar": "غير مرتبطه",
        "ca": "sense relació",
        "cs": "nesouvisející",
        "da": "ingen forbindelse",
        "de": "unabhängig",
        "es": "no relacionado",
        "fr": "sans rapport",
        "hi": "असंबंधित",
        "it": "non correlato",
        "ru": "не связанный",
        "tr": "ilgisiz",
        "zh": "unrelated",
        "zh-CN": "无关",
    },
    "disagree": {
        "ar": "تعارض",
        "ca": "discrepar",
        "cs": "nesouhlasit",
        "da": "være uenig",
        "de": "nicht zustimmen",
        "es": "discrepar",
        "fr": "être en désaccord",
        "hi": "असहमत",
        "it": "disaccordo",
        "ru": "не согласен",
        "tr": "katılmıyorum",
        "zh": "disagree",
        "zh-CN": "不同意",
    },
    "argument_for": {
        "ar": "حجة ل",
        "ca": "argument per",
        "cs": "argument pro",
        "da": "argument for",
        "de": "argument für",
        "es": "argumento a favor",
        "fr": "argument pour",
        "hi": "के लिए तर्क",
        "it": "argomento per",
        "ru": "аргумент в пользу",
        "tr": "için argüman",
        "zh": "argument for",
        "zh-CN": "争辩",
    },
    "against": {
        "ar": "ضد",
        "ca": "en contra",
        "cs": "proti",
        "da": "mod",
        "de": "gegen",
        "es": "en contra",
        "fr": "contre",
        "hi": "विरुद्ध",
        "it": "contro",
        "ru": "против",
        "tr": "karşısında",
        "zh": "against",
        "zh-CN": "反对",
    },
    "favor": {
        "ar": "محاباة",
        "ca": "favor",
        "cs": "laskavost",
        "da": "favor",
        "de": "bevorzugen",
        "es": "favor",
        "fr": "préférer",
        "hi": "एहसान",
        "it": "favore",
        "ru": "услуга",
        "tr": "iyilik",
        "zh-CN": "宠爱",
    },
}
